---
title: "MindPaths_Simulation"
author: "Mohammad Isyroqi Fathan"
date: "October 6, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, include = FALSE}
## Include/Use libraries
library(dplyr)
library(reshape)
library(igraph)
library(ggplot2)
library(ggtern)
library(truncnorm)
library(RSQLite)
library(parallel)
library(rPython)
library(expm)
library(entropy)
library(boot)
```

```{r load_data}
load('../../../RData/NIPS/NIPS_Simulation.RData')
```

```{r Functions}
CalculateAggregatedMultiplexAdjacencyMatrix <- function(networks, weights){
  return(Reduce("+", mapply(function(network, weight){
      return(weight * network)
    }, networks, weights, SIMPLIFY = FALSE))
  )
}

CalculateProbabilityMatrix <- function(adjacency_matrix_aggregate){
  # Probability_i_j = Value_i_j/sum_per_row 
  row_normalizing_constant = 1/apply(adjacency_matrix_aggregate, 1, sum)
  row_normalizing_constant[which(is.infinite(row_normalizing_constant))] <- 0
  return(adjacency_matrix_aggregate * row_normalizing_constant)
}
##============================================================================================================================
### Trace Generation
GenerateTrace <- function(probability_matrix, starting_node, path_length){
  path_trace = list(starting_node)
  for (i in 1:path_length){
    # Traverse one node from current node
    path_trace[[i+1]] = sample(1:dim(probability_matrix)[1], size = 1, prob = probability_matrix[path_trace[[i]], ])
  }
  return(path_trace)
}

## To Do: Fix and optimize how to get Transition Matrix (Problem is how to do pass by reference)
CalculateTraceMatrix <- function(traces, number_of_nodes){
  # # For every trace in traces, create trace_matrix. Then Reduce with "+".
  # Reduce("+", lapply(traces, function(path_trace){
  #   # Create trace_matrix per trace
  #   trace_matrix = matrix(0, number_of_nodes, number_of_nodes)
  #   for (i in 1:(length(path_trace) - 1)){
  #     trace_matrix[path_trace[[i]], path_trace[[i + 1]]] = trace_matrix[path_trace[[i]], path_trace[[i + 1]]] + 1
  #   }
  #   return(trace_matrix)
  # }))
  trace_matrix = matrix(0, number_of_nodes, number_of_nodes)
  for (i in 1:length(traces)){
    for(j in 1:(length(traces[[i]]) - 1)){
      trace_matrix[traces[[i]][[j]], traces[[i]][[j + 1]]] = trace_matrix[traces[[i]][[j]], traces[[i]][[j + 1]]] + 1
    }
  }
  return(trace_matrix)
}

GenerateTraceForRandomNNode <- function(probability_matrix, path_length, number_of_nodes, probability_starting_node = NULL){
  return(lapply(1:number_of_nodes, function(i, probability_matrix, path_length, probability_starting_node){
            # Initialize starting_node to NULL
            starting_node = NULL
            if (is.null(probability_starting_node)) {
              # Sampling starting_node from uniform distribution
              starting_node = sample(1:dim(probability_matrix)[1], 1)
            }
            else {
              # Sampling starting_node from probability_starting_node distribution
              starting_node = sample(1:dim(probability_matrix)[1], 1, prob = probability_starting_node)
            }
            GenerateTrace(probability_matrix, starting_node, path_length)
         }, probability_matrix, path_length, probability_starting_node))
}
##============================================================================================================================
InduceNoiseNetwork <- function(list_network, noise_level, is_rewire = FALSE){
	list_network = lapply(1:length(list_network),
			      function(index, list_network, noise_level){
				      network = list_network[[index]]
				      noise = noise_level[[index]]
				      mean_degree = mean(apply(network, c(1), function(x){sum(x > 0)}))
				      network = apply(network, c(1),
						      function(node, noise, mean_degree){
							      if (is_rewire){
								      num_of_nodes = length(node)
								      node_degree = sum(node > 0)
								      if (node_degree == 0){
									      return(node)
								      }
								      index_edges = which(node > 0)
								      noise = node_degree * noise
								      mask_zero = sample(c(TRUE, FALSE), node_degree, replace = TRUE, prob = c(noise, node_degree - noise))
								      total_zero = sum(mask_zero)
								      node[index_edges[mask_zero]] = 0
								      index_edges = which(node == 0)
								      mask_flip = sample(index_edges, total_zero, replace = FALSE)
								      node[mask_flip] = 1
								      return(node)
							      }
							      else{
								      num_of_nodes = length(node)
								      node_degree = sum(node > 0)
								      if (node_degree == 0){
									      node_degree = mean_degree
								      }
								      noise = node_degree * noise
								      mask_flip = sample(c(TRUE, FALSE), length(node), replace = TRUE, prob = c(noise, num_of_nodes - noise))
								      node[mask_flip] = 1 - node[mask_flip]
								      return(node)
							      }
						      }, noise, mean_degree)
				      return(t(network))
			      }, list_network, noise_level)
	return(list_network)
}
##============================================================================================================================
```


```{r list_simulation}
list_simulation_1 = list()
```

```{r simulation_1}
# Simulate synthetic data unweighted
# Define Variables
list_simulation_1$parameter = list()
list_simulation_1$parameter$network_density_probability = c(0.01, 0.0008, 0.01)
list_simulation_1$parameter$n = 1972
# list_simulation_1$parameter$network_weights = c(0.2, 0.3, 0.5)
list_simulation_1$parameter$network_weights = c(0.63, 0.11, 0.26)
#list_simulation_1$parameter$network_weights = c(0.18, 0.37, 0.45)
list_simulation_1$parameter$number_of_traces = 1000

# ER Network
# Generate Network
list_simulation_1$ER = list()
list_simulation_1$ER$network = lapply(list_simulation_1$parameter$network_density_probability, erdos.renyi.game, n = list_simulation_1$parameter$n, type = c("gnp", "gnm"), directed = TRUE, loops = FALSE)
list_simulation_1$ER$network = lapply(list_simulation_1$ER$network, as_adjacency_matrix, sparse = FALSE)

# Generate Multiplex Network
list_simulation_1$ER$Aggregate = CalculateAggregatedMultiplexAdjacencyMatrix(list_simulation_1$ER$network, list_simulation_1$parameter$network_weights)

# Calculate Probability Matrix
list_simulation_1$ER$Probability = CalculateProbabilityMatrix(list_simulation_1$ER$Aggregate)

# Generate Random Traces
list_simulation_1$ER$traces = GenerateTraceForRandomNNode(list_simulation_1$ER$Probability, 25, list_simulation_1$parameter$number_of_traces)

# Generate Trace Matrix
list_simulation_1$ER$traces_matrix = CalculateTraceMatrix(list_simulation_1$ER$traces, list_simulation_1$parameter$n)

# Regular Network
# Generate Network
list_simulation_1$Regular = list()
list_simulation_1$Regular$network = lapply(list_simulation_1$parameter$network_density_probability * list_simulation_1$parameter$n, sample_k_regular, no.of.nodes = list_simulation_1$parameter$n, directed = TRUE, multiple = FALSE)
list_simulation_1$Regular$network = lapply(list_simulation_1$Regular$network, as_adjacency_matrix, sparse = FALSE)

# Generate Multiplex Network
list_simulation_1$Regular$Aggregate = CalculateAggregatedMultiplexAdjacencyMatrix(list_simulation_1$Regular$network, list_simulation_1$parameter$network_weights)

# Calculate Probability Matrix
list_simulation_1$Regular$Probability = CalculateProbabilityMatrix(list_simulation_1$Regular$Aggregate)

# Generate Random Traces
list_simulation_1$Regular$traces = GenerateTraceForRandomNNode(list_simulation_1$Regular$Probability, 25, list_simulation_1$parameter$number_of_traces)

# Generate Trace Matrix
list_simulation_1$Regular$traces_matrix = CalculateTraceMatrix(list_simulation_1$Regular$traces, list_simulation_1$parameter$n)

# Configuration Model Network
# Generate Network
tmp = list()
tmp$network = list(list_network$eat_network_unweighted > 0,
		   list_network$wn_combined_unweighted > 0,
		   list_network$smallworld_R1 > 0)
tmp$out_degree = lapply(tmp$network, function(x){apply(x, c(1), function(x){sum(x > 0)})})
tmp$in_degree = lapply(tmp$network, function(x){apply(x, c(2), function(x){sum(x > 0)})})
list_simulation_1$Configuration = list()
list_simulation_1$Configuration$network = lapply(1:length(list_simulation_1$parameter$network_density_probability),
						 function(index, out_degree, in_degree){
							 sample_degseq(out_degree[[index]], in_degree[[index]])
						 }, tmp$out_degree, tmp$in_degree)
list_simulation_1$Configuration$network = lapply(list_simulation_1$Configuration$network, as_adjacency_matrix, sparse = FALSE)

# Generate Multiplex Network
list_simulation_1$Configuration$Aggregate = CalculateAggregatedMultiplexAdjacencyMatrix(list_simulation_1$Configuration$network, list_simulation_1$parameter$network_weights)

# Calculate Probability Matrix
list_simulation_1$Configuration$Probability = CalculateProbabilityMatrix(list_simulation_1$Configuration$Aggregate)

# Generate Random Traces
list_simulation_1$Configuration$traces = GenerateTraceForRandomNNode(list_simulation_1$Configuration$Probability, 25, list_simulation_1$parameter$number_of_traces)

# Generate Trace Matrix
list_simulation_1$Configuration$traces_matrix = CalculateTraceMatrix(list_simulation_1$Configuration$traces, list_simulation_1$parameter$n)
rm(tmp)
```

```{r GradientDescent}
ObjectiveFunction <- function(weight_vector, adjacency_matrix_vector, traces_vector, degree_matrix_vector){
	log_adjacency_matrix = log(adjacency_matrix_vector %*% weight_vector)
	log_adjacency_matrix[which(is.infinite(log_adjacency_matrix))] <- 0
	log_degree_matrix = log(degree_matrix_vector %*% weight_vector)
	log_degree_matrix[which(is.infinite(log_degree_matrix))] <- 0
	return( sum(traces_vector * (log_adjacency_matrix - log_degree_matrix)))
	# return( sum(traces_vector * (log(adjacency_matrix_vector %*% weight_vector) - log(degree_matrix_vector %*% weight_vector))))
}

GradientFunction <- function(weight_vector, adjacency_matrix_vector, traces_vector, degree_matrix_vector){
	numerator = as.numeric(adjacency_matrix_vector %*% weight_vector)
	denominator = as.numeric(degree_matrix_vector %*% weight_vector)
	adjacency_over_numerator = adjacency_matrix_vector / numerator
	adjacency_over_numerator[which(!is.finite(adjacency_over_numerator))] <- 0
	degree_over_denominator = degree_matrix_vector / denominator
	degree_over_denominator[which(!is.finite(degree_over_denominator))] <- 0
	result = apply(traces_vector * (adjacency_over_numerator - degree_over_denominator), c(2) , sum)
	return(result)
}

PreprocessA_q <- function(A, weight_vector){
	bound_index = which((weight_vector == 0) | (weight_vector == 1))
	for (i in bound_index){
		tmp_vector = rep(0, length(weight_vector))
		tmp_vector[i] = 1
		A = rbind(A, tmp_vector)
	}
	return(A)
}

GradientDescent <- function(weight_vector, adjacency_matrix, trace_matrix, ObjectiveFunction, GradientFunction, alpha = 0.01, epsilon = 1e-5, max_iteration = 1000, is_print_iteration = FALSE){
	weight_vector = weight_vector / sum(weight_vector)
	# Convert Adjacency Matrix list and trace matrix to adjacency matrix vector and trace vector
	adjacency_matrix_vector = sapply(adjacency_matrix, as.numeric)
	degree_matrix_vector = lapply(adjacency_matrix, function(x){t(apply(x, c(1), function(x){rep(sum(x), length(x))}))})
	degree_matrix_vector = sapply(degree_matrix_vector, as.numeric)
	traces_vector = as.numeric(trace_matrix)

	# Subset data to traces data that exist
	adjacency_matrix_vector = adjacency_matrix_vector[which(traces_vector > 0), ]
	degree_matrix_vector = degree_matrix_vector[which(traces_vector > 0), ]
	traces_vector = traces_vector[which(traces_vector > 0)]

	epsilon = abs(sum(traces_vector) * log(1 - epsilon))

	k = 1
	list_points = list(weight_vector)
	list_gradient_original = list()
	list_gradient = list()
	list_objective = list()

	# Initial Calculation
	list_gradient_original[[k]] = GradientFunction(list_points[[k]], adjacency_matrix_vector, traces_vector, degree_matrix_vector)
	length_gradient_original = sqrt(sum(list_gradient_original[[k]] ^ 2))
	list_gradient_original[[k]] = list_gradient_original[[k]] / sqrt(sum(list_gradient_original[[k]] ^ 2))
	list_objective[[k]] = ObjectiveFunction(list_points[[k]], adjacency_matrix_vector, traces_vector, degree_matrix_vector)

	# Build A_q matrix
	A = matrix(1, 1, length(adjacency_matrix))

	#while ((k < max_iteration) & (sqrt(sum(gradient ^ 2)))){
	while ((k <= max_iteration) & ( length_gradient_original > epsilon )){
		if (is_print_iteration) {print(k)}
		list_gradient_original[[k]] = GradientFunction(list_points[[k]], adjacency_matrix_vector, traces_vector, degree_matrix_vector)
		length_gradient_original = sqrt(sum(list_gradient_original[[k]] ^ 2))
		list_gradient_original[[k]] = list_gradient_original[[k]] / sqrt(sum(list_gradient_original[[k]] ^ 2))
		list_objective[[k]] = ObjectiveFunction(list_points[[k]], adjacency_matrix_vector, traces_vector, degree_matrix_vector)

		# Preprocessed A_q
		A_q = PreprocessA_q(A, list_points[[k]])

		# Compute P matrix
		P = diag(max(dim(A_q))) - (t(A_q) %*% solve(A_q %*% t(A_q)) %*% A_q)

		# Compute projected gradient
		list_gradient[[k]] = P %*% list_gradient_original[[k]]

		list_points[[k + 1]] = list_points[[k]] + alpha * list_gradient[[k]]

		k = k + 1
	}

	# Remove Last Point
	list_points[[k]] = NULL

	result_dataframe = Reduce(rbind, mapply(function(point, likelihood){
		result = data.frame(t(point))
		result$value = likelihood
		return(result)
	  }, list_points, list_objective, SIMPLIFY = FALSE))
	result_dataframe$iteration = 1:dim(result_dataframe)[1]

	list_result = list()
	list_result$result_dataframe = result_dataframe
	list_result$list_gradient_original = list_gradient_original
	list_result$list_gradient = list_gradient
	return(list_result)

}
```

```{r noise_test}
CheckParamKey <- function(list_param, key){
	return(if (is.null(list_param[[key]])) {stop(paste("Missing parameter: ", key))} else {list_param[[key]]})
}
TestNoise <- function(noise_level, ...){
	# Get Parameters
	list_param = list(...)
	list_network = CheckParamKey(list_param, "list_network")
	traces_matrix = CheckParamKey(list_param, "traces_matrix")
	starting_point = CheckParamKey(list_param, "starting_point")
	epsilon = CheckParamKey(list_param, "epsilon")
	is_rewire = if (is.null(list_param[["is_rewire"]])) {FALSE} else {list_param[["is_rewire"]]}
	
	# Induce Noise and Compute
	list_network = InduceNoiseNetwork(list_network, noise_level, is_rewire = is_rewire)
	return(GradientDescent(starting_point, list_network, traces_matrix, ObjectiveFunction, GradientFunction, epsilon = epsilon))
}
postProcessGradientDescent <- function(result){
	result = result$result_dataframe
	result = result[dim(result)[1], ]
	return(result)
}
SweepNoiseLevel <- function(sequence_noise, postProcessFunction, no_of_cores, noise_sample, ...){
	mclapply(mc.cores = no_of_cores, sequence_noise,
			     function(noise_level_1, ...){
				     return(
					    lapply(sequence_noise,
						   function(noise_level_2, noise_level_1, ...){
							   return(
								  lapply(sequence_noise,
									 function(noise_level_3, noise_level_2, noise_level_1, ...){
										 print(c(noise_level_1, noise_level_2, noise_level_3))
										 result_sample = lapply(1:noise_sample,
													function(x, noise_level_3, noise_level_2, noise_level_1, ...){
														result = TestNoise(c(noise_level_1, noise_level_2, noise_level_3), ...)
														result = postProcessFunction(result)
														return(c(noise_level_1, noise_level_2, noise_level_3, result))
													}, noise_level_3, noise_level_2, noise_level_1, ...)
										 return (result_sample)
									 }, noise_level_2, noise_level_1, ...)
								  )
						   }, noise_level_1, ...)
					    )
			     }, ...)
}
ConvertNoiseResultToMatrix <- function(result){
	colnames_result = names(result[[1]][[1]][[1]][[1]])
	result = matrix(unlist(result), ncol = length(result[[1]][[1]][[1]][[1]]), byrow = TRUE)
	colnames(result) = colnames_result
	colnames(result)[1:3] = c("noise_layer_1", "noise_layer_2", "noise_layer_3")
	return(result)
}
runTestNoise <- function(sequence_noise, postProcessFunction, no_of_cores, noise_sample, ...){
	starting_point = runif(3)
	starting_point = starting_point/sum(starting_point)
	start_time = Sys.time()
	result = SweepNoiseLevel(sequence_noise, postProcessFunction, no_of_cores, noise_sample, starting_point = starting_point, ...)
	finish_time = Sys.time()
	print(finish_time - start_time)
	result = ConvertNoiseResultToMatrix(result)
	final_result = list()
	final_result$sequence_noise = sequence_noise
	final_result$noise_sample = noise_sample
	final_result$starting_point = starting_point
	final_result$start_time = start_time
	final_result$finish_time = finish_time
	final_result$result = result
	return(final_result)
}
```

```{r run_test_noise}
no_of_cores = detectCores()
sequence_noise = seq(0, 1, 1/20)
noise_sample = 1
test_noise_result = runTestNoise(sequence_noise, postProcessGradientDescent, no_of_cores, noise_sample,
				 list_network = list_simulation_1$ER$network,
				 traces_matrix = list_simulation_1$ER$traces_matrix,
				 epsilon = 1e-4)
```

```{r run_test_noise_multiple_samples}
no_of_cores = detectCores()
sequence_noise = seq(0, 1, 1/5)
noise_sample = 10
test_noise_result_multiple_samples = runTestNoise(sequence_noise, postProcessGradientDescent, no_of_cores, noise_sample,
						  list_network = list_simulation_1$ER$network,
						  traces_matrix = list_simulation_1$ER$traces_matrix,
						  epsilon = 1e-4)
```

```{r run_test_noise_rewire}
no_of_cores = detectCores()
sequence_noise = seq(0, 1, 1/20)
noise_sample = 1
test_noise_result_rewire = runTestNoise(sequence_noise, postProcessGradientDescent, no_of_cores, noise_sample,
					list_network = list_simulation_1$ER$network,
					traces_matrix = list_simulation_1$ER$traces_matrix,
					epsilon = 1e-4,
					is_rewire = TRUE)
```

```{r run_test_noise_multiple_samples_rewire}
no_of_cores = detectCores()
sequence_noise = seq(0, 1, 1/5)
noise_sample = 10
test_noise_result_multiple_samples_rewire = runTestNoise(sequence_noise, postProcessGradientDescent, no_of_cores, noise_sample,
							 list_network = list_simulation_1$ER$network,
							 traces_matrix = list_simulation_1$ER$traces_matrix,
							 epsilon = 1e-4,
							 is_rewire = TRUE)
```

```{r test}
test_result = GradientDescent(c(0.3, 0.3, 0.4), list_simulation_1$ER$network, list_simulation_1$ER$traces_matrix, ObjectiveFunction, GradientFunction, epsilon = 1e-4)
```

```{r MindPaths_Simulation_Data}
starting_point = runif(3)
starting_point = starting_point / sum(starting_point)
list_GradientDescent_result = list()
list_GradientDescent_result[[1]] = GradientDescent(starting_point, list_simulation_1$ER$network, list_simulation_1$ER$traces_matrix, ObjectiveFunction, GradientFunction, epsilon = 1e-4)
list_GradientDescent_result[[2]] = GradientDescent(starting_point, list_simulation_2$ER$network, list_simulation_2$ER$traces_matrix, ObjectiveFunction, GradientFunction, epsilon = 1e-4)
starting_point = runif(4)
starting_point = starting_point / sum(starting_point)
list_GradientDescent_result[[3]] = GradientDescent(starting_point, list_simulation_3$network, list_simulation_3$traces_matrix, ObjectiveFunction, GradientFunction, epsilon = 1e-4)
list_GradientDescent_result[[4]] = GradientDescent(starting_point, list_simulation_4$network, list_simulation_4$traces_matrix, ObjectiveFunction, GradientFunction, epsilon = 1e-4)
list_GradientDescent_result[[5]] = GradientDescent(starting_point, list_simulation_5$network, list_simulation_5$traces_matrix, ObjectiveFunction, GradientFunction, epsilon = 1e-4)
```

```{r save_data}
save(list = ls(), file = 'RData/GradientDescent.RData')
```
