---
title: "MindPaths_Simulation"
author: "Mohammad Isyroqi Fathan"
date: "October 6, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, include = FALSE}
## Include/Use libraries
library(coda)
library(dplyr)
library(reshape)
library(igraph)
library(ggplot2)
library(ggtern)
library(truncnorm)
library(RSQLite)
library(parallel)
library(rPython)
library(expm)
library(entropy)
library(boot)
```

```{r load_data}
load('../../RData/NIPS_Simulation.RData')
```

```{r Functions}
CalculateAggregatedMultiplexAdjacencyMatrix <- function(networks, weights){
  return(Reduce("+", mapply(function(network, weight){
      return(weight * network)
    }, networks, weights, SIMPLIFY = FALSE))
  )
}

CalculateProbabilityMatrix <- function(adjacency_matrix_aggregate){
  # Probability_i_j = Value_i_j/sum_per_row 
  row_normalizing_constant = 1/apply(adjacency_matrix_aggregate, 1, sum)
  row_normalizing_constant[which(is.infinite(row_normalizing_constant))] <- 0
  return(adjacency_matrix_aggregate * row_normalizing_constant)
}
##============================================================================================================================
### Trace Generation
GenerateTrace <- function(probability_matrix, starting_node, path_length){
  path_trace = list(starting_node)
  for (i in 1:path_length){
    # Traverse one node from current node
    path_trace[[i+1]] = sample(1:dim(probability_matrix)[1], size = 1, prob = probability_matrix[path_trace[[i]], ])
  }
  return(path_trace)
}

## To Do: Fix and optimize how to get Transition Matrix (Problem is how to do pass by reference)
CalculateTraceMatrix <- function(traces, number_of_nodes){
  # # For every trace in traces, create trace_matrix. Then Reduce with "+".
  # Reduce("+", lapply(traces, function(path_trace){
  #   # Create trace_matrix per trace
  #   trace_matrix = matrix(0, number_of_nodes, number_of_nodes)
  #   for (i in 1:(length(path_trace) - 1)){
  #     trace_matrix[path_trace[[i]], path_trace[[i + 1]]] = trace_matrix[path_trace[[i]], path_trace[[i + 1]]] + 1
  #   }
  #   return(trace_matrix)
  # }))
  trace_matrix = matrix(0, number_of_nodes, number_of_nodes)
  for (i in 1:length(traces)){
    for(j in 1:(length(traces[[i]]) - 1)){
      trace_matrix[traces[[i]][[j]], traces[[i]][[j + 1]]] = trace_matrix[traces[[i]][[j]], traces[[i]][[j + 1]]] + 1
    }
  }
  return(trace_matrix)
}

GenerateTraceForRandomNNode <- function(probability_matrix, path_length, number_of_nodes, probability_starting_node = NULL){
  return(lapply(1:number_of_nodes, function(i, probability_matrix, path_length, probability_starting_node){
            # Initialize starting_node to NULL
            starting_node = NULL
            if (is.null(probability_starting_node)) {
              # Sampling starting_node from uniform distribution
              starting_node = sample(1:dim(probability_matrix)[1], 1)
            }
            else {
              # Sampling starting_node from probability_starting_node distribution
              starting_node = sample(1:dim(probability_matrix)[1], 1, prob = probability_starting_node)
            }
            GenerateTrace(probability_matrix, starting_node, path_length)
         }, probability_matrix, path_length, probability_starting_node))
}
##============================================================================================================================
CalculateLogLikelihood <- function(weight_vector, adjacency_matrix_vector, traces_vector, degree_matrix_vector){
	log_adjacency_matrix = log(adjacency_matrix_vector %*% weight_vector)
	log_adjacency_matrix[which(is.infinite(log_adjacency_matrix))] <- 0
	log_degree_matrix = log(degree_matrix_vector %*% weight_vector)
	log_degree_matrix[which(is.infinite(log_degree_matrix))] <- 0
	# return(sum(traces_vector * (log(adjacency_matrix_vector %*% weight_vector) - log(degree_matrix_vector %*% weight_vector))))
	return(sum(traces_vector * (log_adjacency_matrix - log_degree_matrix)))
}
##============================================================================================================================
SweepAnalysis <- function(adjacency_matrix, traces, likelihood_function, number_of_points = 100) {
	# Convert Adjacency Matrix list to (nxn) x number of layer matrix. Also Compute degree matrix converted to same dimension matrix
	adjacency_matrix_vector = sapply(adjacency_matrix, as.numeric)
	degree_matrix_vector = lapply(adjacency_matrix, function(x){t(apply(x, c(1), function(x){rep(sum(x), length(x))}))})
	degree_matrix_vector = sapply(degree_matrix_vector, as.numeric)
	traces_vector = as.numeric(traces)

	# Subset data to traces data that exist
	adjacency_matrix_vector = adjacency_matrix_vector[ which(traces_vector > 0), ]
	degree_matrix_vector = degree_matrix_vector[which(traces_vector > 0), ]
	traces_vector = traces_vector[ which(traces_vector > 0) ]
	result = mclapply(mc.cores = no_of_cores, seq(0, 1, 1/number_of_points), function(weight_1, likelihood_function, adjacency_matrix_vector, traces_vector, degree_matrix_vector){
			 print(weight_1)
			 lapply(seq(0, 1 - weight_1, 1/number_of_points), function(weight_2, weight_1, likelihood_function, adjacency_matrix_vector, traces_vector, degree_matrix_vector){
				list(c(weight_1, weight_2, 1-(weight_1 + weight_2)), likelihood_function(c(weight_1, weight_2, 1-(weight_1 + weight_2)), adjacency_matrix_vector, traces_vector, degree_matrix_vector))
			}, weight_1, likelihood_function, adjacency_matrix_vector, traces_vector, degree_matrix_vector)
	  }, likelihood_function, adjacency_matrix_vector, traces_vector, degree_matrix_vector)
	df = data.frame()
	alpha = 1/number_of_points
	for (i in 1:length(result)) {
		for (j in 1:length(result[[i]])){
			df = rbind(df, data.frame(w1 = result[[i]][[j]][[1]][[1]], w2 = result[[i]][[j]][[1]][[2]], w3 = result[[i]][[j]][[1]][[3]], likelihood = result[[i]][[j]][[2]]))
		}
	}
	return(df)
}
##============================================================================================================================
InduceNoiseNetwork <- function(list_network, noise_level){
	list_network = lapply(1:length(list_network),
			      function(index, list_network, noise_level){
				      network = list_network[[index]]
				      noise = noise_level[[index]]
				      mean_degree = mean(apply(network, c(1), function(x){sum(x > 0)}))
				      network = apply(network, c(1),
						      function(node, noise, mean_degree){
							      num_of_nodes = length(node)
							      node_degree = sum(node > 0)
							      if (node_degree == 0){
								      node_degree = mean_degree
							      }
							      noise = node_degree * noise
							      mask_flip = sample(c(TRUE, FALSE), length(node), replace = TRUE, prob = c(noise, num_of_nodes - noise))
							      node[mask_flip] = 1 - node[mask_flip]
							      return(node)
						      }, noise, mean_degree)
				      return(t(network))
			      }, list_network, noise_level)
	return(list_network)
}
```


```{r list_simulation}
list_simulation_1 = list()
```

```{r simulation_1}
# Simulate synthetic data unweighted
# Define Variables
list_simulation_1$parameter = list()
list_simulation_1$parameter$network_density_probability = c(0.01, 0.0008, 0.01)
list_simulation_1$parameter$n = 1972
# list_simulation_1$parameter$network_weights = c(0.2, 0.3, 0.5)
list_simulation_1$parameter$network_weights = c(0.63, 0.11, 0.26)
#list_simulation_1$parameter$network_weights = c(0.18, 0.37, 0.45)
list_simulation_1$parameter$number_of_traces = 1000

# ER Network
# Generate Network
list_simulation_1$ER = list()
list_simulation_1$ER$network = lapply(list_simulation_1$parameter$network_density_probability, erdos.renyi.game, n = list_simulation_1$parameter$n, type = c("gnp", "gnm"), directed = TRUE, loops = FALSE)
list_simulation_1$ER$network = lapply(list_simulation_1$ER$network, as_adjacency_matrix, sparse = FALSE)

# Generate Multiplex Network
list_simulation_1$ER$Aggregate = CalculateAggregatedMultiplexAdjacencyMatrix(list_simulation_1$ER$network, list_simulation_1$parameter$network_weights)

# Calculate Probability Matrix
list_simulation_1$ER$Probability = CalculateProbabilityMatrix(list_simulation_1$ER$Aggregate)

# Generate Random Traces
list_simulation_1$ER$traces = GenerateTraceForRandomNNode(list_simulation_1$ER$Probability, 25, list_simulation_1$parameter$number_of_traces)

# Generate Trace Matrix
list_simulation_1$ER$traces_matrix = CalculateTraceMatrix(list_simulation_1$ER$traces, list_simulation_1$parameter$n)

# Regular Network
# Generate Network
list_simulation_1$Regular = list()
list_simulation_1$Regular$network = lapply(list_simulation_1$parameter$network_density_probability * list_simulation_1$parameter$n, sample_k_regular, no.of.nodes = list_simulation_1$parameter$n, directed = TRUE, multiple = FALSE)
list_simulation_1$Regular$network = lapply(list_simulation_1$Regular$network, as_adjacency_matrix, sparse = FALSE)

# Generate Multiplex Network
list_simulation_1$Regular$Aggregate = CalculateAggregatedMultiplexAdjacencyMatrix(list_simulation_1$Regular$network, list_simulation_1$parameter$network_weights)

# Calculate Probability Matrix
list_simulation_1$Regular$Probability = CalculateProbabilityMatrix(list_simulation_1$Regular$Aggregate)

# Generate Random Traces
list_simulation_1$Regular$traces = GenerateTraceForRandomNNode(list_simulation_1$Regular$Probability, 25, list_simulation_1$parameter$number_of_traces)

# Generate Trace Matrix
list_simulation_1$Regular$traces_matrix = CalculateTraceMatrix(list_simulation_1$Regular$traces, list_simulation_1$parameter$n)

# Configuration Model Network
# Generate Network
tmp = list()
tmp$network = list(list_network$eat_network_unweighted > 0,
		   list_network$wn_combined_unweighted > 0,
		   list_network$smallworld_R1 > 0)
tmp$out_degree = lapply(tmp$network, function(x){apply(x, c(1), function(x){sum(x > 0)})})
tmp$in_degree = lapply(tmp$network, function(x){apply(x, c(2), function(x){sum(x > 0)})})
list_simulation_1$Configuration = list()
list_simulation_1$Configuration$network = lapply(1:length(list_simulation_1$parameter$network_density_probability),
						 function(index, out_degree, in_degree){
							 sample_degseq(out_degree[[index]], in_degree[[index]])
						 }, tmp$out_degree, tmp$in_degree)
list_simulation_1$Configuration$network = lapply(list_simulation_1$Configuration$network, as_adjacency_matrix, sparse = FALSE)

# Generate Multiplex Network
list_simulation_1$Configuration$Aggregate = CalculateAggregatedMultiplexAdjacencyMatrix(list_simulation_1$Configuration$network, list_simulation_1$parameter$network_weights)

# Calculate Probability Matrix
list_simulation_1$Configuration$Probability = CalculateProbabilityMatrix(list_simulation_1$Configuration$Aggregate)

# Generate Random Traces
list_simulation_1$Configuration$traces = GenerateTraceForRandomNNode(list_simulation_1$Configuration$Probability, 25, list_simulation_1$parameter$number_of_traces)

# Generate Trace Matrix
list_simulation_1$Configuration$traces_matrix = CalculateTraceMatrix(list_simulation_1$Configuration$traces, list_simulation_1$parameter$n)
rm(tmp)
```

```{r analyze}
no_of_cores = detectCores()
number_of_points = 200
test_result = SweepAnalysis(list_simulation_1$ER$network, list_simulation_1$ER$traces_matrix, CalculateLogLikelihood, number_of_points)
```

```{r noise_test}
TestNoise <- function(list_network, traces_matrix, noise_level, number_of_points){
	list_network = InduceNoiseNetwork(list_network, noise_level)
	return(SweepAnalysis(list_network, traces_matrix, CalculateLogLikelihood, number_of_points))
}
```

```{r run_test_noise}
no_of_cores = detectCores()
test_noise_result = mclapply(mc.cores = no_of_cores, seq(0, 0.1, 0.1/100),
			     function(noise_level, list_simulation, number_of_points){
				     return(TestNoise(list_simulation$network, list_simulation$traces_matrix,
						      rep(noise_level, length(list_simulation$network)), number_of_points))
			     }, list_simulation_1$ER, number_of_points)
```

```{r process_test_noise}
test_noise_result_removed_zero = lapply(test_noise_result,
					   function(result){
						   result = result[which(result$w1 != 0 & result$w2 != 0 & result$w3 != 0), ]
						   result = result[order(result), ]
						   return(result)
					   })
test_noise_max = lapply(test_noise_result_removed_zero,
			 function(result){
				 result[dim(result)[1], 1:3]
			 })
```


```{r MindPaths_Simulation_Data}
number_of_points = 200
list_Sweep_result = list()
list_Sweep_result[[1]] = SweepAnalysis(list_simulation_1$ER$network, list_simulation_1$ER$traces_matrix, CalculateLogLikelihood, number_of_points)
list_Sweep_result[[2]] = SweepAnalysis(list_simulation_2$ER$network, list_simulation_2$ER$traces_matrix, CalculateLogLikelihood, number_of_points)
# list_Sweep_result[[3]] = SweepAnalysis(list_simulation_3$network, list_simulation_3$traces_matrix, CalculateLogLikelihood, number_of_points)
# list_Sweep_result[[4]] = SweepAnalysis(list_simulation_4$network, list_simulation_4$traces_matrix, CalculateLogLikelihood, number_of_points)
# list_Sweep_result[[5]] = SweepAnalysis(list_simulation_5$network, list_simulation_5$traces_matrix, CalculateLogLikelihood, number_of_points)
```

```{r save data}
save(list = ls(), file = 'RData/Sweep.RData')
```
